# 버전 정보
version: 0.2

# 빌드 단계를 정의
phases:
  # 빌드 전 단계
  pre_build:
    commands:
      - npm install -g npm@9.6.7  # npm을 이용하여 필요한 패키지들을 설치
      - npm i @fortawesome/fontawesome-svg-core@6.4.2
      - npm i @fortawesome/free-solid-svg-icons@6.4.2
      - npm i @fortawesome/react-fontawesome@0.2.0
      - npm install @reduxjs/toolkit@1.9.7
      - npm install @stomp/stompjs
      - npm install axios
      - npm install date-fns
      - npm i http-proxy-middleware
      - npm install jwt-decode
      - npm i moment
      - npm install peerjs
      - npm install react-calendar
      - npm install react-cookie
      - npm install react-icons
      - npm i redux 
      - npm i react-redux
      - npm i redux-logger
      - npm i react-router-dom
      - npm install --save-dev redux-devtools
      - npm i redux-persist
      - npm install sockjs-client
  # 빌드 단계
  build:
    commands:
      - npm run build  # npm 스크립트를 통해 빌드 수행

# 빌드 후 생성된 결과물에 대한 정보
artifacts:
  files:
    - '**/*'  # 모든 파일과 디렉토리를 포함
  base-directory: build  # 결과물이 위치한 기본 디렉토리는 'build' 
