# 버전 정보
version: 0.2

# 빌드 단계를 정의
phases:
  # 빌드 전 단계
  pre_build:
    commands:
      - npm install -g npm@9.6.7 --legacy-peer-deps  # npm을 이용하여 필요한 패키지들을 설치
      - npm i @fortawesome/fontawesome-svg-core --legacy-peer-deps
      - npm i @fortawesome/free-solid-svg-icons --legacy-peer-deps
      - npm i @fortawesome/react-fontawesome --legacy-peer-deps
      - npm install @reduxjs/toolkit --legacy-peer-deps
      - npm install @stomp/stompjs --legacy-peer-deps
      - npm install axios --legacy-peer-deps
      - npm install date-fns --legacy-peer-deps
      - npm i http-proxy-middleware --legacy-peer-deps
      - npm install jwt-decode --legacy-peer-deps
      - npm i moment --legacy-peer-deps
      - npm install peerjs --legacy-peer-deps
      - npm install react-calendar --legacy-peer-deps
      - npm install react-cookie --legacy-peer-deps
      - npm install react-icons --legacy-peer-deps
      - npm i redux --legacy-peer-deps
      - npm i react-redux --legacy-peer-deps
      - npm i redux-logger --legacy-peer-deps
      - npm i react-router-dom --legacy-peer-deps
      - npm install --save-dev redux-devtools --legacy-peer-deps
      - npm i redux-persist --legacy-peer-deps
      - npm install sockjs-client --legacy-peer-deps
  # 빌드 단계
  build:
    commands:
      - npm run build  # npm 스크립트를 통해 빌드 수행

# 빌드 후 생성된 결과물에 대한 정보
artifacts:
  files:
    - '**/*'  # 모든 파일과 디렉토리를 포함
  base-directory: build  # 결과물이 위치한 기본 디렉토리는 'build' 
